title: "David Población"

url: https://davidpob99.github.io

header_pages:
  - index.md
  - about.md

google_analytics: UA-88563869-9

twitter: davidpblcrd
github: davidpob99
linkedin: davidpoblacion
paypal: davidpoblacion
email: davidpblcrd [ arroba ] protonmail [ punto ] com
bitcoin: bc1qav4dg0sc4st5jg2kh3jwyjfws5rn3d3cgkd6nh

lang: es

style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
